FROM ubuntu:latest

USER root

ARG home_dir=/home

ENV WEB_DOCUMENT_ROOT=$home_dir

ENV TERM=xterm\
    TZ=America/Argentina/Cordoba\
    DEBIAN_FRONTEND=noninteractive

WORKDIR /var/www/html/

RUN apt-get update

RUN apt-get install -y curl

RUN curl -Lo /bin/firebase https://firebase.tools/bin/linux/latest

RUN chmod +x /bin/firebase

ENTRYPOINT ["tail", "-f", "/dev/null"]
